### ISSUE TITLE
Para centrar mejor 'redes'

### ISSUE THREAD

**Issue by jotaaloud** [YoussefAKQ/YoussefAKQ.github.io#2]
Donde pone 'justify-content' está escrito 'space-between'. Prueba con 'space-around' o 'space-evenly'! Seguro que te gustará.<br />
![Captura de pantalla 2024-04-03 142516](https://github.com/YoussefAKQ/YoussefAKQ.github.io/assets/58860938/cb1686b6-ea57-4dff-b413-0e5938fd6ffa)

**Comment by YoussefAKQ** [comment]
Gracias.
