### ISSUE TITLE
Para centrar mejor 'redes'

### ISSUE THREAD

**Issue by codejovz** [YoussefAKQ/YoussefAKQ.github.io#4]
Donde pone 'justify-content', está escrito 'space-between'. Prueba con 'space-around' o 'space-evenly'! Seguro que te gusta. <br />

![Captura de pantalla 2024-04-03 142516](https://github.com/YoussefAKQ/YoussefAKQ.github.io/assets/58860938/18de96f1-c364-4e94-a328-c7533a7936bc)

**Comment by YoussefAKQ** [comment]
Gracias.

**Comment by YoussefAKQ** [comment]
Gracias
